Repository bionanek/glasswitch-orders-web, pull requests merged in 2019-05, with the labels that each got.

#24 create customersService file to keep static methods used component-wi…
  .editorconfig
  .eslintrc
  src/components/customers/crud/CustomerDetail.js
  src/components/customers/crud/CustomerEdit.js
  src/components/customers/customersService.js
Labels: bug

#48 POST new product
  src/components/common/simpleList/SimpleList.scss
  src/components/products/Products.js
  src/components/products/Products.scss
  src/components/products/components/modalCreate/ModalCreateProduct.js
  src/components/products/components/modalCreate/ModalCreateProduct.scss
  src/components/products/list/ProductsList.js
  src/components/products/list/ProductsList.scss
  src/utils/api/productsApiService.js
Labels: feature

#56 Task/image upload
  src/components/products/ProductsUtils.js
  src/components/products/components/modalCreate/ModalCreateProduct.js
  src/components/products/crud/ProductDetail.js
  src/components/products/crud/ProductEdit.js
Labels: feature

#57 orders list. get all & delete order
  src/App.js
  src/components/common/navigation/Navigation.js
  src/components/orders/Orders.js
  src/components/orders/Orders.scss
  src/components/orders/list/OrdersList.js
  src/utils/api/ordersApiService.js
Labels: feature

#58 Task/order details
  src/App.js
  src/components/orders/crud/OrderDetail.js
  src/components/orders/crud/OrderDetail.scss
  src/utils/api/ordersApiService.js
Labels: feature

#61 grid view for products. layout is able to change via buttons on the top.
  src/components/products/components/tile/ProductTile.js
  src/components/products/components/tile/ProductTile.scss
  src/components/products/components/tile/ProductTileElement.js
  src/components/products/components/tile/ProductTileElement.scss
  src/components/products/list/ProductsList.js
  src/components/products/list/ProductsList.scss
Labels: feature

#60 Feature/orders
  src/App.js
  src/components/common/navigation/Navigation.js
  src/components/orders/Orders.js
  src/components/orders/Orders.scss
  src/components/orders/crud/OrderDetail.js
  src/components/orders/crud/OrderDetail.scss
  src/components/orders/list/OrdersList.js
  src/utils/api/ordersApiService.js
Labels: feature

#62 renamed tile into grid. removed unnecessary Row from the List.
  src/components/products/components/grid/ProductGrid.js
  src/components/products/components/grid/ProductGridElement.js
  src/components/products/components/tile/ProductTile.scss
  src/components/products/components/tile/ProductTileElement.scss
  src/components/products/crud/ProductEdit.js
  src/components/products/list/ProductsList.js
  src/components/products/list/ProductsList.scss
Labels: improvement

#64 conflict fix
  src/App.js
  src/components/common/navigation/Navigation.js
  src/components/orders/Orders.js
  src/components/orders/Orders.scss
  src/components/orders/crud/OrderDetail.js
  src/components/orders/crud/OrderDetail.scss
  src/components/orders/list/OrdersList.js
  src/utils/api/ordersApiService.js
Labels: bug

#49 Feature/products
  src/App.js
  src/components/common/ImageElement.js
  src/components/common/modals/imageModal/ImageModal.js
  src/components/common/modals/imageModal/ImageModal.scss
  src/components/common/simpleList/SimpleList.scss
  src/components/products/Products.js
  src/components/products/Products.scss
  src/components/products/ProductsData.js
  src/components/products/ProductsUtils.js
  src/components/products/components/grid/ProductGrid.js
  src/components/products/components/grid/ProductGridElement.js
  src/components/products/components/modalCreate/ModalCreateProduct.js
  src/components/products/components/modalCreate/ModalCreateProduct.scss
  src/components/products/crud/ProductDetail.js
  src/components/products/crud/ProductDetail.scss
  src/components/products/crud/ProductEdit.js
  src/components/products/crud/ProductEdit.scss
  src/components/products/list/ProductsList.js
  src/components/products/list/ProductsList.scss
  src/utils/api/productsApiService.js
Labels: feature
